a = Analysis(['code/main.py'],
             pathex=['.'],
             binaries=[],
             datas=[
                 ('graphics/apple.png', 'graphics'),
                 ('graphics/snake/*', 'graphics/snake'),
                 ('audio/*', 'audio')
             ],
             hiddenimports=['code.settings'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=None,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
          cipher=None)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='PySnake',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=False,
          onefile=True,
        )
